[virtualenvs]
create = false

[tool.poetry]
name = "backend"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110"
uvicorn = "^0.27"
numpy = "^1.26"
pymongo = "^4.6"

[tool.poetry.dev-dependencies]
pytest = "^8.0"
black = "^24.0"
